### ISSUE TITLE
部署时报错 No default language could be detected for this app.

### ISSUE THREAD

**Issue by troilus** [sayomelu/heroku-miniflux#1]
-----> Building on the Heroku-20 stack
 !     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed

**Comment by sayomelu** [comment]
must deploy in main branch

**Comment by troilus** [comment]
> must deploy in main branch
我是直接点击的这个链接进去部署的：
deploy with button
	https://heroku.com/deploy
只有填写一些参数的地方，是在哪里设置来从main branch部署呢？

**Comment by sayomelu** [comment]
左上角有一个 action，点一下选择 main。

On Feb 16, 2021, at 22:51, Li <notifications@github.com> wrote:

﻿

must deploy in main branch
我是直接点击的这个链接进去部署的：
deploy with button
https://heroku.com/deploy
只有填写一些参数的地方，是在哪里设置来从main branch部署呢？

**Comment by troilus** [comment]
选择main branch还是部署失败了，提示：
-----> Building on the Heroku-20 stack
-----> Go app detected
-----> Fetching jq... done
-----> Fetching stdlib.sh.v8... done
-----> 
       Detected go modules via go.mod
-----> 
       Detected Module Name: miniflux.app
-----> 
-----> New Go Version, clearing old cache
-----> Installing go1.11.13
-----> Fetching go1.11.13.linux-amd64.tar.gz... done
-----> Determining packages to install
 !     Push rejected, failed to compile Go app.
 !     Push failed

There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

**Comment by sayomelu** [comment]
尝试重新 fork 一下, 现在更新了 [readme.md](https://github.com/sayomelu/heroku-miniflux/blob/action/readme.md). 我这里可以成功部署. 如果依然有问题可以用其他方式私聊.

**Comment by troilus** [comment]
已经可以了，谢谢
