### ISSUE TITLE
not worked for me :(

### ISSUE THREAD

**Issue by kakamband** [sayomelu/heroku-miniflux#2]
hi sayomelu,
i'm go to deploy step by step using your readme.MD tutorial note step by step & switch to main branch but after deploy my dyno say application error
please if any env value or buildpack or any addon resources must be set in dyno setting tell me otherwise help me plz
my dyno build log is : 

-----> Building on the Heroku-20 stack

-----> Determining which buildpack to use for this app

-----> Go app detected

-----> Fetching jq... done

-----> Fetching stdlib.sh.v8... done

-----> 

       Detected go modules via go.mod

-----> 

       Detected Module Name: miniflux.app

-----> 

-----> New Go Version, clearing old cache

-----> Installing go1.16.1

-----> Fetching go1.16.1.linux-amd64.tar.gz... done

-----> Determining packages to install

       

       Detected the following main packages to install:

       		miniflux.app

       

-----> Running: go install -v -tags heroku miniflux.app 

golang.org/x/sys/internal/unsafeheader

miniflux.app/version

golang.org/x/sys/unix

miniflux.app/config

github.com/lib/pq/oid

github.com/lib/pq/scram

github.com/lib/pq

golang.org/x/crypto/ssh/terminal

miniflux.app/locale

miniflux.app/logger

miniflux.app/database

github.com/beorn7/perks/quantile

github.com/cespare/xxhash/v2

google.golang.org/protobuf/internal/detrand

google.golang.org/protobuf/internal/errors

google.golang.org/protobuf/internal/pragma

google.golang.org/protobuf/encoding/protowire

google.golang.org/protobuf/internal/flags

google.golang.org/protobuf/internal/set

google.golang.org/protobuf/internal/version

github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg

google.golang.org/protobuf/reflect/protoreflect

github.com/prometheus/common/model

google.golang.org/protobuf/reflect/protoregistry

google.golang.org/protobuf/internal/strs

google.golang.org/protobuf/internal/encoding/text

google.golang.org/protobuf/internal/encoding/messageset

google.golang.org/protobuf/internal/genid

google.golang.org/protobuf/internal/mapsort

google.golang.org/protobuf/internal/fieldsort

google.golang.org/protobuf/runtime/protoiface

google.golang.org/protobuf/internal/descfmt

google.golang.org/protobuf/proto

google.golang.org/protobuf/internal/descopts

google.golang.org/protobuf/internal/encoding/defval

github.com/prometheus/procfs/internal/fs

github.com/prometheus/procfs/internal/util

github.com/prometheus/procfs

google.golang.org/protobuf/encoding/prototext

google.golang.org/protobuf/internal/filedesc

golang.org/x/crypto/acme

google.golang.org/protobuf/internal/encoding/tag

google.golang.org/protobuf/internal/impl

golang.org/x/text/transform

golang.org/x/text/unicode/bidi

golang.org/x/text/secure/bidirule

golang.org/x/text/unicode/norm

golang.org/x/net/idna

golang.org/x/crypto/acme/autocert

golang.org/x/crypto/blowfish

golang.org/x/crypto/bcrypt

miniflux.app/crypto

golang.org/x/net/html/atom

golang.org/x/net/html

google.golang.org/protobuf/internal/filetype

google.golang.org/protobuf/runtime/protoimpl

github.com/golang/protobuf/proto

google.golang.org/protobuf/types/known/anypb

github.com/golang/protobuf/ptypes/any

google.golang.org/protobuf/types/known/durationpb

github.com/golang/protobuf/ptypes/duration

google.golang.org/protobuf/types/known/timestamppb

github.com/matttproud/golang_protobuf_extensions/pbutil

golang.org/x/text/encoding/internal/identifier

github.com/golang/protobuf/ptypes/timestamp

golang.org/x/text/encoding

github.com/golang/protobuf/ptypes

github.com/prometheus/client_model/go

golang.org/x/text/encoding/internal

golang.org/x/text/encoding/charmap

github.com/prometheus/client_golang/prometheus/internal

github.com/prometheus/common/expfmt

golang.org/x/text/encoding/japanese

github.com/prometheus/client_golang/prometheus

golang.org/x/text/encoding/korean

golang.org/x/text/encoding/simplifiedchinese

golang.org/x/text/encoding/traditionalchinese

golang.org/x/text/internal/utf8internal

golang.org/x/text/runes

golang.org/x/text/internal/tag

golang.org/x/text/internal/language

golang.org/x/text/encoding/unicode

miniflux.app/errors

miniflux.app/timer

miniflux.app/url

miniflux.app/timezone

github.com/gorilla/mux

golang.org/x/text/internal/language/compact

github.com/prometheus/client_golang/prometheus/promhttp

golang.org/x/text/language

golang.org/x/text/encoding/htmlindex

golang.org/x/net/html/charset

miniflux.app/http/client

miniflux.app/http/request

miniflux.app/model

miniflux.app/http/response

miniflux.app/http/response/json

miniflux.app/storage

miniflux.app/http/response/xml

miniflux.app/reader/browser

github.com/andybalholm/cascadia

github.com/PuerkitoBio/goquery

miniflux.app/metric

miniflux.app/reader/date

miniflux.app/reader/media

miniflux.app/reader/sanitizer

miniflux.app/reader/icon

miniflux.app/reader/encoding

miniflux.app/reader/xml

miniflux.app/reader/atom

miniflux.app/reader/json

miniflux.app/reader/rdf

miniflux.app/reader/rss

golang.org/x/text/internal/format

golang.org/x/text/language/display

miniflux.app/reader/parser

miniflux.app/reader/rewrite

miniflux.app/reader/readability

miniflux.app/reader/scraper

miniflux.app/reader/opml

miniflux.app/reader/subscription

miniflux.app/validator

miniflux.app/integration/instapaper

miniflux.app/integration/nunuxkeeper

miniflux.app/integration/pinboard

miniflux.app/integration/pocket

miniflux.app/integration/wallabag

miniflux.app/integration

miniflux.app/fever

github.com/felixge/httpsnoop

github.com/rylans/getlang

miniflux.app/reader/processor

miniflux.app/reader/handler

github.com/golang/gddo/httputil/header

github.com/mitchellh/go-server-timing

miniflux.app/worker

miniflux.app/api

miniflux.app/http/cookie

miniflux.app/http/response/html

miniflux.app/http/route

github.com/pquerna/cachecontrol/cacheobject

golang.org/x/net/context/ctxhttp

golang.org/x/oauth2/internal

github.com/pquerna/cachecontrol

golang.org/x/crypto/ed25519

golang.org/x/crypto/pbkdf2

gopkg.in/square/go-jose.v2/cipher

golang.org/x/oauth2

gopkg.in/square/go-jose.v2/json

miniflux.app/proxy

miniflux.app/template

miniflux.app/ui/form

miniflux.app/ui/session

github.com/tdewolff/parse/v2

github.com/tdewolff/parse/v2/buffer

gopkg.in/square/go-jose.v2

github.com/tdewolff/parse/v2/strconv

github.com/tdewolff/minify/v2

github.com/tdewolff/parse/v2/css

github.com/tdewolff/minify/v2/css

github.com/coreos/go-oidc

github.com/tdewolff/parse/v2/js

miniflux.app/oauth2

mvdan.cc/xurls/v2

miniflux.app/service/scheduler

github.com/tdewolff/minify/v2/js

miniflux.app/ui/static

miniflux.app/ui/view

miniflux.app/ui

miniflux.app/service/httpd

miniflux.app/cli

miniflux.app

       

       Installed the following binaries:

       		./bin/miniflux.app

-----> Discovering process types

       Procfile declares types -> web

-----> Compressing...

       Done: 9.8M

-----> Launching...

       Released v3

       https://khabarkhan.herokuapp.com/ deployed to Heroku

waiting for your response
finest regards
goodbye

**Comment by sayomelu** [comment]
do you change any **Config Vars**?

**Comment by sayomelu** [comment]
action updated, try redeploy?

**Comment by sayomelu** [comment]
no reply
