### ISSUE TITLE
数据库行数超出免费计划限制

### ISSUE THREAD

**Issue by sunete** [sayomelu/heroku-miniflux#3]
程序稳定运行了半个月，订阅源大概有 80 多个。最近收到 Heroku 邮件提示： The database contains 10,578 rows, exceeding the Hobby-dev plan limit of 10,000.

在网上搜索解决办法，看到这篇文章： [Heroku Database Size Warning: Finding the Problem](http://rvlasveld.github.io/blog/2013/09/30/heroku-database-size-warning-finding-the-problem/)

文章介绍了手动删除的方法，请问是否有更简单的自动或手动删除数据的方法？

**Comment by sayomelu** [comment]
- to cleanup manually History -> Flush history.
- to cleanup automatically, set ‘CLEANUP_ARCHIVE_READ_DAYS’ ‘CLEANUP_ARCHIVE_UNREAD_DAYS’ variable.

**Comment by sunete** [comment]
Thanks!
